---
services:
  workflow.pacta.report:
    build: .
    # stdin_open: true
    # tty: true
    # entrypoint: ["R", "--args"]
    # command: '{\"portfolio_files\": \"default_portfolio.csv\", \"inherit\": \"GENERAL_2023Q4\"}'
    # entrypoint: "bash"
    # command: "/workflow.pacta.report/input_dir/default_config.json"
    environment:
      LOG_LEVEL: TRACE
      ANALYSIS_OUTPUT_DIR: "/mnt/analysis_output_dir"
      BENCHMARKS_DIR: "/mnt/benchmarks_dir"
      REPORT_OUTPUT_DIR: "/mnt/report_output_dir"
      SUMMARY_OUTPUT_DIR: "/mnt/summary_output_dir"
    volumes:
      - type: bind
        source: ${benchmarks_dir:-./benchmarks_dir}
        target: /mnt/benchmarks_dir/
        read_only: true
      - type: bind
        source: ${analysis_output_dir:-./analysis_output_dir}
        target: /mnt/analysis_output_dir
        read_only: true
      - type: bind
        source: ${report_output_dir:-./report_output_dir}
        target: /mnt/report_output_dir
        read_only: false
      - type: bind
        source: ${summary_output_dir:-./summary_output_dir}
        target: /mnt/summary_output_dir
        read_only: false
